version = 0.1
[default.deploy.parameters]
stack_name = "hdi"
resolve_s3 = true
s3_prefix = "hdi"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
parameter_overrides = "HDIS3BucketName=\"hdidata\""
